-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 12:52:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IpestDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IpestDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IpestDB` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `IpestDB` ;

-- -----------------------------------------------------
-- Table `IpestDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IpestDB`.`User` (
  `idUser` INT NOT NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IpestDB`.`Dashboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IpestDB`.`Dashboard` (
  `idDashboard` INT NOT NULL,
  `locatio` VARCHAR(45) NULL,
  `lastVisit` DATE NULL,
  `TechID` INT NULL,
  `batteryLevel` INT NULL,
  `trapStatus` VARCHAR(45) NULL,
  PRIMARY KEY (`idDashboard`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
